version: "3"
services:

  wordpress:
    image: wordpress:4-php5.6-apache
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_PASSWORD=root

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
